apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "first-pipeline"
  namespace: ad_user1
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2,
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A hello world pipeline.",
      "name": "My first pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2}
spec:
  entrypoint: first-pipeline
  arguments:
    parameters:
    - {name: namespace, value: ""}  
  templates:
  - name: echo
    container:
      args: [echo "hello world"]
      command: [sh, -c]
      image: library/bash:4.4.23
      resources:               
        limits:
          memory: 32Mi
          cpu: 100m
  - name: first-pipeline
    dag:
      tasks:
      - {name: echo, template: echo}
      
  arguments:
    parameters: []

